# use C-a like screen
unbind-key C-b
set-option -g prefix C-a
bind-key C-a last-window
bind-key a send-prefix

set-window-option -g mode-keys vi
set-window-option -g visual-bell on
set -g history-limit 10000

set -g default-shell /usr/bin/fish

# bind-key w choose-window -F "#(window_index):#(pane_current_path} #(pane_current_command}"
